FROM node:alpine
ENV GitCloneURL noURL
ENV PATHToGitClone data

RUN apk add --no-cache git
RUN apk add --no-cache openssh
#RUN mkdir /usr/emptyStorage
#WORKDIR /usr/emptyStorage

#COPY GitCloneCrypto.sh ./

# $GitCloneOrgHyperledgeURL - url to crypto/tx files
# $PATHToGitClone
# container-ul nu trebuie repornit
# volume empty dir, shared prin volume name
#
# git clone https://github.com/bmastahac/HyperledgerFabric.git  data
CMD [ "sh" , "-c", "git clone $GitCloneURL  $PATHToGitClone; tail -f /dev/null" ]



